sudo: required

services:
    - docker

script:
    - make docker-test

notifications:
    email:
        on_success: change
        on_failure: always

after_script:
    - test $TRAVIS_BRANCH != 'master' && make trigger-build TOKEN=$OBS_TEST_TOKEN
    - test $TRAVIS_BRANCH == 'master' && make trigger-build TOKEN=$OBS_RELEASE_TOKEN
